spring:
  profiles:
    active:
      - dev
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7071.com:7071/eureka/
---
server:
  port: 8201
 spring:
   profiles: dev
   application:
     name: cloud-config-client


---
server:
  port: 8202
 spring:
   profiles: test
   application:
     name: cloud-config-client